# Generated by Django 3.1.7 on 2021-04-01 13:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('studentId', models.ImageField(upload_to='images/')),
                ('profilePic', models.ImageField(upload_to='images/')),
                ('momo_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('hall_of_affiliation', models.CharField(choices=[('0P', 'Opoku ware'), ('AU', 'Autonomy'), ('AT', 'Atwima')], max_length=20)),
                ('residential_Address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CS', 'Cosmetics'), ('PH', 'Pharmacy'), ('ELC', 'Electronics'), ('OT', 'other')], default='OT', max_length=11)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_of_category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('description', models.TextField(max_length=300)),
                ('location', models.CharField(max_length=20)),
                ('momo_number', models.CharField(default='', max_length=10)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.shop_category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('price_of_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shop')),
            ],
        ),
    ]
