# Generated by Django 3.1.7 on 2021-04-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_of_product',
            new_name='price',
        ),
    ]
