# Generated by Django 3.1.7 on 2021-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210401_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_api',
            field=models.CharField(default='', max_length=100),
        ),
    ]
