# Generated by Django 3.1.7 on 2021-04-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shop_shop_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=100)),
                ('secrete_key', models.CharField(max_length=100)),
                ('encription_Key', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.api_key'),
        ),
    ]
