# Generated by Django 3.1.7 on 2021-04-15 14:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210410_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_of_category')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_api',
        ),
        migrations.AddField(
            model_name='shop',
            name='encription_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='public_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='secret_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shop_category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='momo_number',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Api_key',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
